# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ubuntu:latest

pipelines:
  default:
    - parallel:
      - step:
          name: 'Login to docker'
          script:
            - pipe: microsoft/azure-cli-run:1.1.0
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                CLI_COMMAND: 'az account show'
      - step:
          name: Run AZ script
          image: mcr.microsoft.com/azure-cli
          script:
            - az login --service-principal --username $AZURE_APP_ID --password $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD containerreg2201120.azurecr.io
            - docker build . -t containerreg2201120.azurecr.io/my-app-bitbucket:latest
            - docker push containerreg2201120.azurecr.io/my-app-bitbucket:latest

     